name: Docker

on:
  workflow_dispatch:
    inputs:
      images:
        description: "Images to build"
        required: true
        type: choice
        options:
          - app
          - builder
          - base
          - seed
          - all
        default: app
      tag:
        description: "Image tag"
        required: false
        type: string
        default: latest

jobs:
  build:
    uses: ./.github/workflows/docker-build.yml
    with:
      images: ${{ inputs.images }}
      tag: ${{ inputs.tag }}
    permissions:
      contents: read
      packages: write
